AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SendOtpByConnect

  Sample SAM Template for SendOtpByConnect

Globals:
  Function:
    Timeout: 10

Resources:
  SendOtpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Policies:
        - AmazonConnectFullAccess
        - AmazonDynamoDBFullAccess
  CognitoOtpTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: CognitoOtpTable
      PrimaryKey:
        Name: username
        Type: String
  UserPoolLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: cognito-idp.amazonaws.com
      FunctionName: !Ref SendOtpFunction
      SourceArn: !Sub 'arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*'
  SendOtpUserPool:
    Type: AWS::Cognito::UserPool
    Properties: 
      UserPoolName: SendOtpUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      LambdaConfig:
        PreSignUp: !GetAtt SendOtpFunction.Arn
  SendOtpClient:
    Type: AWS::Cognito::UserPoolClient
    Properties: 
      ClientName: SendOtpClient
      UserPoolId: !Ref SendOtpUserPool 
  ConfirmOtpFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code_for_confirm_otp/
      Handler: app.lambda_handler
      Runtime: ruby2.5
      Events: 
        MyAPI:
          Type: Api
          Properties:
            Path: /otp
            Method: Post
            RestApiId: !Ref ConfirmOtpApi
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonCognitoPowerUser
      Environment:
        Variables:
          UserPoolId: !Ref SendOtpUserPool
  ConfirmOtpApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      DefinitionBody:
         Fn::Transform:
           Name: AWS::Include
           Parameters:
             Location: swagger.yaml

Outputs:
  UserPoolId: 
    Value: !Ref SendOtpUserPool
  ClientId: 
    Value: !Ref SendOtpClient
  TableName:
    Value: !Ref CognitoOtpTable
